apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cosmos-statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      value: https://
    - name: database
      value: ordersDb
    - name: collection
      value: orders
    - name: masterKey
      value: 